// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ActivityCenterAllocateRatio
    {
        public long ActivityCenterAllocateRatioId { get; set; }
        public long PeriodDataId { get; set; }
        public long FromActivityCenterId { get; set; }
        public long ToActivityCenterId { get; set; }
        public float Ratio { get; set; }
        public long? DriverId { get; set; }
        public float? DriverValue { get; set; }
        public long AllocateLevel { get; set; }
        public string CostType { get; set; }
        public bool IsStop { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? ToMachineGroupId { get; set; }
        public decimal? Amount { get; set; }
        public string Currency { get; set; }
        public float? ComplexityValue { get; set; }
        public float? DriverValueInit { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual ActivityCenter FromActivityCenter { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ActivityCenter ToActivityCenter { get; set; }
        public virtual MachineGroup ToMachineGroup { get; set; }
    }
}