// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ActivityTree
    {
        public long ActivityTreeId { get; set; }
        public long PeriodDataId { get; set; }
        public long CompanyId { get; set; }
        public long? ActivityId1 { get; set; }
        public string ActivityNo1 { get; set; }
        public string Description1 { get; set; }
        public string ActivityNo2 { get; set; }
        public string Description2 { get; set; }
        public long? ActivityId2 { get; set; }
        public string ActivityNo3 { get; set; }
        public string Description3 { get; set; }
        public long? ActivityId3 { get; set; }
        public string ActivityNo4 { get; set; }
        public string Description4 { get; set; }
        public long? ActivityId4 { get; set; }
        public string ActivityNo5 { get; set; }
        public string Description5 { get; set; }
        public long? ActivityId5 { get; set; }
        public string ActivityName1 { get; set; }
        public string ActivityName2 { get; set; }
        public string ActivityName3 { get; set; }
        public string ActivityName4 { get; set; }
        public string ActivityName5 { get; set; }
    }
}