// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ActivityCenterWorkRate
    {
        public ActivityCenterWorkRate()
        {
            ActivityCost = new HashSet<ActivityCost>();
        }

        public long ActivityCenterWorkRateId { get; set; }
        public long PeriodDataId { get; set; }
        public long ActivityCenterId { get; set; }
        public long? MachineGroupId { get; set; }
        public decimal StdRate { get; set; }
        public decimal ActRate { get; set; }
        public decimal TotalStdWorkHour { get; set; }
        public decimal TotalActWorkHour { get; set; }
        public decimal? TotalCost { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }

        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual MachineGroup MachineGroup { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ICollection<ActivityCost> ActivityCost { get; set; }
    }
}