// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Activity
    {
        public Activity()
        {
            ActivityCost = new HashSet<ActivityCost>();
            ActualActivityTime = new HashSet<ActualActivityTime>();
            ActualWorkHour = new HashSet<ActualWorkHour>();
            CustomerServiceCost = new HashSet<CustomerServiceCost>();
            DriverActivity = new HashSet<DriverActivity>();
            InverseParentActivity = new HashSet<Activity>();
            MachineGroupActivity = new HashSet<MachineGroupActivity>();
            ProjectCost = new HashSet<ProjectCost>();
            StandardActivityTime = new HashSet<StandardActivityTime>();
            StandardWorkHour = new HashSet<StandardWorkHour>();
            ValueChain = new HashSet<ValueChain>();
        }

        public long ActivityId { get; set; }
        public string ActivityNo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public long? ParentActivityId { get; set; }
        public long? ActivityDriverId { get; set; }
        public string QualityAttr { get; set; }
        public string ProductionAttr { get; set; }
        public string ValueAddedAttr { get; set; }
        public string ServiceAttr { get; set; }
        public string ReasonGroup { get; set; }
        public string ValueObjectType { get; set; }
        public long? ServiceDriverId { get; set; }
        public bool IsStdGap { get; set; }
        public long ObjectClassId { get; set; }
        public string UserProperty1 { get; set; }
        public string UserProperty2 { get; set; }
        public string UserProperty3 { get; set; }
        public string UserProperty4 { get; set; }
        public string UserProperty5 { get; set; }
        public string UserProperty6 { get; set; }
        public string UserProperty7 { get; set; }
        public string UserProperty8 { get; set; }
        public string UserProperty9 { get; set; }
        public string UserProperty10 { get; set; }
        public string UserProperty11 { get; set; }
        public string UserProperty12 { get; set; }
        public string UserProperty13 { get; set; }
        public string UserProperty14 { get; set; }
        public string UserProperty15 { get; set; }
        public string UserProperty16 { get; set; }
        public string UserProperty17 { get; set; }
        public string UserProperty18 { get; set; }
        public string UserProperty19 { get; set; }
        public string UserProperty20 { get; set; }
        public string ProductCostType { get; set; }

        public virtual Driver ActivityDriver { get; set; }
        public virtual Company Company { get; set; }
        public virtual Activity ParentActivity { get; set; }
        public virtual Driver ServiceDriver { get; set; }
        public virtual ICollection<ActivityCost> ActivityCost { get; set; }
        public virtual ICollection<ActualActivityTime> ActualActivityTime { get; set; }
        public virtual ICollection<ActualWorkHour> ActualWorkHour { get; set; }
        public virtual ICollection<CustomerServiceCost> CustomerServiceCost { get; set; }
        public virtual ICollection<DriverActivity> DriverActivity { get; set; }
        public virtual ICollection<Activity> InverseParentActivity { get; set; }
        public virtual ICollection<MachineGroupActivity> MachineGroupActivity { get; set; }
        public virtual ICollection<ProjectCost> ProjectCost { get; set; }
        public virtual ICollection<StandardActivityTime> StandardActivityTime { get; set; }
        public virtual ICollection<StandardWorkHour> StandardWorkHour { get; set; }
        public virtual ICollection<ValueChain> ValueChain { get; set; }
    }
}