// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ActivityCenterTree
    {
        public long ActreeId { get; set; }
        public long PeriodDataId { get; set; }
        public long CompanyId { get; set; }
        public long BusinessUnitId { get; set; }
        public long? ActivityCenterId1 { get; set; }
        public string ActivityCenterNo1 { get; set; }
        public string Description1 { get; set; }
        public string ActivityCenterNo2 { get; set; }
        public string Description2 { get; set; }
        public long? ActivityCenterId2 { get; set; }
        public string ActivityCenterNo3 { get; set; }
        public string Description3 { get; set; }
        public long? ActivityCenterId3 { get; set; }
        public string ActivityCenterNo4 { get; set; }
        public string Description4 { get; set; }
        public long? ActivityCenterId4 { get; set; }
        public string ActivityCenterNo5 { get; set; }
        public string Description5 { get; set; }
        public long? ActivityCenterId5 { get; set; }
        public long? ActivityCenterId6 { get; set; }
        public long? ActivityCenterId7 { get; set; }
        public long? ActivityCenterId8 { get; set; }
        public long? ActivityCenterId9 { get; set; }
        public long? ActivityCenterId10 { get; set; }
        public long? ActivityCenterId11 { get; set; }
        public long? ActivityCenterId12 { get; set; }
        public long? ActivityCenterId13 { get; set; }
        public long? ActivityCenterId14 { get; set; }
        public long? ActivityCenterId15 { get; set; }
        public string ActivityCenterNo6 { get; set; }
        public string ActivityCenterNo7 { get; set; }
        public string ActivityCenterNo8 { get; set; }
        public string ActivityCenterNo9 { get; set; }
        public string ActivityCenterNo10 { get; set; }
        public string ActivityCenterNo11 { get; set; }
        public string ActivityCenterNo12 { get; set; }
        public string ActivityCenterNo13 { get; set; }
        public string ActivityCenterNo14 { get; set; }
        public string ActivityCenterNo15 { get; set; }
        public string Description6 { get; set; }
        public string Description7 { get; set; }
        public string Description8 { get; set; }
        public string Description9 { get; set; }
        public string Description10 { get; set; }
        public string Description11 { get; set; }
        public string Description12 { get; set; }
        public string Description13 { get; set; }
        public string Description14 { get; set; }
        public string Description15 { get; set; }
    }
}