// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ActivityCost
    {
        public long ActivityCostId { get; set; }
        public long ActivityCenterWorkRateId { get; set; }
        public long ActivityId { get; set; }
        public string CostType { get; set; }
        public decimal Amount { get; set; }
        public decimal StdAmount { get; set; }
        public decimal WorkHour { get; set; }
        public float Ratio { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public decimal ValueObjectAmount { get; set; }
        public decimal ExtraWorkHour { get; set; }
        public long? SupportedActivityCenterId { get; set; }
        public long? SupportedMachineGroupId { get; set; }
        public string Currency { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual ActivityCenterWorkRate ActivityCenterWorkRate { get; set; }
    }
}