// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ActualActivityTime
    {
        public long ActualActivityTimeId { get; set; }
        public int DateCode { get; set; }
        public string Shift { get; set; }
        public long ActivityId { get; set; }
        public long? ActivityCenterId { get; set; }
        public long? MachineGroupId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public int Seconds { get; set; }
        public string Duration { get; set; }
        public long? ValueObjectId { get; set; }
        public long? ProductId { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public string Label1 { get; set; }
        public string Label2 { get; set; }
        public string Label3 { get; set; }
        public string Label4 { get; set; }
        public string Label5 { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual MachineGroup MachineGroup { get; set; }
    }
}