// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class BusinessUnitResource
    {
        public long BusinessUnitResourceId { get; set; }
        public string BusinessUnitResourceNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long ResourceId { get; set; }
        public long BusinessUnitId { get; set; }
        public string ValueObjectType { get; set; }
        public long? ResourceDriverId { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Driver ResourceDriver { get; set; }
    }
}