// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Classification
    {
        public Classification()
        {
            InverseParentClassification = new HashSet<Classification>();
        }

        public long ClassificationId { get; set; }
        public string ClassificationNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? ParentClassificationId { get; set; }
        public long ClassificationTreeId { get; set; }
        public string ClassificationNo1 { get; set; }
        public string ClassificationNo2 { get; set; }
        public string ClassificationNo3 { get; set; }
        public string ClassificationNo4 { get; set; }
        public string ClassificationNo5 { get; set; }
        public string ClassificationNo6 { get; set; }
        public string ClassificationNo7 { get; set; }
        public string ClassificationNo8 { get; set; }
        public string ClassificationNo9 { get; set; }

        public virtual ClassificationTree ClassificationTree { get; set; }
        public virtual Classification ParentClassification { get; set; }
        public virtual ICollection<Classification> InverseParentClassification { get; set; }
    }
}