// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Company
    {
        public Company()
        {
            Activity = new HashSet<Activity>();
            ActivityCenter = new HashSet<ActivityCenter>();
            BusinessUnit = new HashSet<BusinessUnit>();
            ClassificationTree = new HashSet<ClassificationTree>();
            Dictionary = new HashSet<Dictionary>();
            Driver = new HashSet<Driver>();
            Employee = new HashSet<Employee>();
            EntityParameter = new HashSet<EntityParameter>();
            EntityProperty = new HashSet<EntityProperty>();
            Function = new HashSet<Function>();
            Message = new HashSet<Message>();
            Model = new HashSet<Model>();
            ObjectClass = new HashSet<ObjectClass>();
            Period = new HashSet<Period>();
            PickList = new HashSet<PickList>();
            Resource = new HashSet<Resource>();
            UserGroup = new HashSet<UserGroup>();
            ValueChain = new HashSet<ValueChain>();
            ValueObject = new HashSet<ValueObject>();
        }

        public long CompanyId { get; set; }
        public string CompanyNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public string Currency { get; set; }
        public string Industry { get; set; }
        public int ResourceLevel { get; set; }
        public int ActivityLevel { get; set; }
        public int ActivityCenterLevel { get; set; }
        public byte[] LogoFile { get; set; }
        public string Locale { get; set; }

        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<ActivityCenter> ActivityCenter { get; set; }
        public virtual ICollection<BusinessUnit> BusinessUnit { get; set; }
        public virtual ICollection<ClassificationTree> ClassificationTree { get; set; }
        public virtual ICollection<Dictionary> Dictionary { get; set; }
        public virtual ICollection<Driver> Driver { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<EntityParameter> EntityParameter { get; set; }
        public virtual ICollection<EntityProperty> EntityProperty { get; set; }
        public virtual ICollection<Function> Function { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Model> Model { get; set; }
        public virtual ICollection<ObjectClass> ObjectClass { get; set; }
        public virtual ICollection<Period> Period { get; set; }
        public virtual ICollection<PickList> PickList { get; set; }
        public virtual ICollection<Resource> Resource { get; set; }
        public virtual ICollection<UserGroup> UserGroup { get; set; }
        public virtual ICollection<ValueChain> ValueChain { get; set; }
        public virtual ICollection<ValueObject> ValueObject { get; set; }
    }
}