// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class CustomerServiceCostSum
    {
        public long PeriodDataId { get; set; }
        public long? BusinessUnitId { get; set; }
        public long CustomerId { get; set; }
        public long? ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal AllocateAmount { get; set; }
        public decimal DirectAmount { get; set; }
        public decimal UnitAmount { get; set; }
        public decimal AllocateStdAmount { get; set; }
        public decimal DirectStdAmount { get; set; }
        public decimal UnitStdAmount { get; set; }
        public string Currency { get; set; }
        public string ValueChain { get; set; }
    }
}