// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class CustomerServiceCost
    {
        public long CustomerServiceCostId { get; set; }
        public long? BusinessUnitId { get; set; }
        public long PeriodDataId { get; set; }
        public long CustomerId { get; set; }
        public long? ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal AllocateAmount { get; set; }
        public decimal DirectAmount { get; set; }
        public decimal UnitAmount { get; set; }
        public decimal AllocateStdAmount { get; set; }
        public decimal DirectStdAmount { get; set; }
        public decimal UnitStdAmount { get; set; }
        public string Currency { get; set; }
        public long? ResourceId { get; set; }
        public long? ActivityId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? DriverId { get; set; }
        public float? Ratio { get; set; }
        public float? DriverValue { get; set; }
        public float? ComplexityValue { get; set; }
        public float? DriverValueInit { get; set; }
        public string ValueChain { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ValueObject Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Product { get; set; }
        public virtual Resource Resource { get; set; }
    }
}