// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class DataSourceSetting
    {
        public long DataSourceSettingId { get; set; }
        public string DataSourceSettingNo { get; set; }
        public string Description { get; set; }
        public long CompanyId { get; set; }
        public string SelectSql { get; set; }
        public string FromSql { get; set; }
        public string WhereSql { get; set; }
        public string GroupBySql { get; set; }
        public string HavingSql { get; set; }
        public string OrderBySql { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public int? Index { get; set; }
    }
}