// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Driver
    {
        public Driver()
        {
            ActivityActivityDriver = new HashSet<Activity>();
            ActivityCenter = new HashSet<ActivityCenter>();
            ActivityCenterAllocateRatio = new HashSet<ActivityCenterAllocateRatio>();
            ActivityCenterCost = new HashSet<ActivityCenterCost>();
            ActivityServiceDriver = new HashSet<Activity>();
            BusinessUnitResource = new HashSet<BusinessUnitResource>();
            CustomerServiceCost = new HashSet<CustomerServiceCost>();
            DriverActivity = new HashSet<DriverActivity>();
            ProjectCostAllocation = new HashSet<ProjectCostAllocation>();
            ResourceResourceDriver = new HashSet<Resource>();
            ResourceServiceDriver = new HashSet<Resource>();
            ValueObject = new HashSet<ValueObject>();
            ValueObjectCost = new HashSet<ValueObjectCost>();
        }

        public long DriverId { get; set; }
        public string DriverNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public string DriverEntityName { get; set; }
        public string Formula { get; set; }
        public long ObjectClassId { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<Activity> ActivityActivityDriver { get; set; }
        public virtual ICollection<ActivityCenter> ActivityCenter { get; set; }
        public virtual ICollection<ActivityCenterAllocateRatio> ActivityCenterAllocateRatio { get; set; }
        public virtual ICollection<ActivityCenterCost> ActivityCenterCost { get; set; }
        public virtual ICollection<Activity> ActivityServiceDriver { get; set; }
        public virtual ICollection<BusinessUnitResource> BusinessUnitResource { get; set; }
        public virtual ICollection<CustomerServiceCost> CustomerServiceCost { get; set; }
        public virtual ICollection<DriverActivity> DriverActivity { get; set; }
        public virtual ICollection<ProjectCostAllocation> ProjectCostAllocation { get; set; }
        public virtual ICollection<Resource> ResourceResourceDriver { get; set; }
        public virtual ICollection<Resource> ResourceServiceDriver { get; set; }
        public virtual ICollection<ValueObject> ValueObject { get; set; }
        public virtual ICollection<ValueObjectCost> ValueObjectCost { get; set; }
    }
}