// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Employee
    {
        public long EmployeeId { get; set; }
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string Description { get; set; }
        public long CompanyId { get; set; }
        public long ActivityCenterId { get; set; }
        public long? UserId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }

        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}