// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class EntityClassificationTree
    {
        public long EntityClassificationTreeId { get; set; }
        public string EntityName { get; set; }
        public long? ObjectClassId { get; set; }
        public string Property { get; set; }
        public long ClassificationTreeId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }

        public virtual ClassificationTree ClassificationTree { get; set; }
        public virtual ObjectClass ObjectClass { get; set; }
    }
}