// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class EntityParameterValue
    {
        public long EntityParameterValueId { get; set; }
        public string EntityParameterValueNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long EntityParameterId { get; set; }
        public double ParameterValue { get; set; }
        public long EntityPropertyId { get; set; }
        public string EntityPropertyValue { get; set; }

        public virtual EntityParameter EntityParameter { get; set; }
        public virtual EntityProperty EntityProperty { get; set; }
    }
}