// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Function
    {
        public Function()
        {
            UserGroupFunction = new HashSet<UserGroupFunction>();
        }

        public long FunctionId { get; set; }
        public string FunctionNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<UserGroupFunction> UserGroupFunction { get; set; }
    }
}