// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class MachineGroup
    {
        public MachineGroup()
        {
            ActivityCenterAllocateRatio = new HashSet<ActivityCenterAllocateRatio>();
            ActivityCenterCost = new HashSet<ActivityCenterCost>();
            ActivityCenterWorkRate = new HashSet<ActivityCenterWorkRate>();
            ActualActivityTime = new HashSet<ActualActivityTime>();
            ActualWorkHourMachineGroup = new HashSet<ActualWorkHour>();
            ActualWorkHourSupportedMachineGroup = new HashSet<ActualWorkHour>();
            DriverActivity = new HashSet<DriverActivity>();
            MachineGroupActivityFromMachineGroup = new HashSet<MachineGroupActivity>();
            MachineGroupActivityMainMachineGroup = new HashSet<MachineGroupActivity>();
            ProjectCost = new HashSet<ProjectCost>();
            ResourceAdjustmentCost = new HashSet<ResourceAdjustmentCost>();
            StandardActivityTime = new HashSet<StandardActivityTime>();
            StandardWorkHour = new HashSet<StandardWorkHour>();
        }

        public long MachineGroupId { get; set; }
        public string MachineGroupNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long ActivityCenterId { get; set; }
        public string MachineGroupType { get; set; }
        public int? Quantity { get; set; }
        public long ObjectClassId { get; set; }
        public string UserProperty1 { get; set; }
        public string UserProperty2 { get; set; }
        public string UserProperty3 { get; set; }
        public string UserProperty4 { get; set; }
        public string UserProperty5 { get; set; }
        public string UserProperty6 { get; set; }
        public string UserProperty7 { get; set; }
        public string UserProperty8 { get; set; }
        public string UserProperty9 { get; set; }
        public string UserProperty10 { get; set; }
        public string UserProperty11 { get; set; }
        public string UserProperty12 { get; set; }
        public string UserProperty13 { get; set; }
        public string UserProperty14 { get; set; }
        public string UserProperty15 { get; set; }
        public string UserProperty16 { get; set; }
        public string UserProperty17 { get; set; }
        public string UserProperty18 { get; set; }
        public string UserProperty19 { get; set; }
        public string UserProperty20 { get; set; }

        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual ICollection<ActivityCenterAllocateRatio> ActivityCenterAllocateRatio { get; set; }
        public virtual ICollection<ActivityCenterCost> ActivityCenterCost { get; set; }
        public virtual ICollection<ActivityCenterWorkRate> ActivityCenterWorkRate { get; set; }
        public virtual ICollection<ActualActivityTime> ActualActivityTime { get; set; }
        public virtual ICollection<ActualWorkHour> ActualWorkHourMachineGroup { get; set; }
        public virtual ICollection<ActualWorkHour> ActualWorkHourSupportedMachineGroup { get; set; }
        public virtual ICollection<DriverActivity> DriverActivity { get; set; }
        public virtual ICollection<MachineGroupActivity> MachineGroupActivityFromMachineGroup { get; set; }
        public virtual ICollection<MachineGroupActivity> MachineGroupActivityMainMachineGroup { get; set; }
        public virtual ICollection<ProjectCost> ProjectCost { get; set; }
        public virtual ICollection<ResourceAdjustmentCost> ResourceAdjustmentCost { get; set; }
        public virtual ICollection<StandardActivityTime> StandardActivityTime { get; set; }
        public virtual ICollection<StandardWorkHour> StandardWorkHour { get; set; }
    }
}