// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Model
    {
        public Model()
        {
            PeriodData = new HashSet<PeriodData>();
        }

        public long ModelId { get; set; }
        public string ModelNo { get; set; }
        public long CompanyId { get; set; }
        public string Comment { get; set; }
        public long SnapshotTransactionId { get; set; }
        public bool? IsEffective { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<PeriodData> PeriodData { get; set; }
    }
}