// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ModelSnapshot
    {
        public long ModelId { get; set; }
        public string EntityName { get; set; }
        public long EntityId { get; set; }
        public long? TransactionId { get; set; }
    }
}