// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class MoListTmp
    {
        public long BusinessUnitId { get; set; }
        public long ManufactureOrderId { get; set; }
    }
}