// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class MoMaterialCost
    {
        public long MoMaterialCostId { get; set; }
        public long PeriodId { get; set; }
        public long ManufactureOrderId { get; set; }
        public long MaterialId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long BusinessUnitId { get; set; }
        public decimal PurchaseAmount { get; set; }
        public long LastPeriodDataId { get; set; }
        public bool IsRework { get; set; }
        public decimal ActivityAmount { get; set; }
        public decimal ResourceAmount { get; set; }
        public decimal SupplierAmount { get; set; }
        public decimal Moaamount { get; set; }
        public decimal Momamount { get; set; }
        public decimal Tpamount { get; set; }
        public string CostFrom { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ValueObject ManufactureOrder { get; set; }
        public virtual ValueObject Material { get; set; }
        public virtual Period Period { get; set; }
    }
}