// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class MoProductCostVer
    {
        public long MoProductCostId { get; set; }
        public long ManufactureOrderId { get; set; }
        public long PeriodId { get; set; }
        public decimal Quantity { get; set; }
        public long ProductId { get; set; }
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long BusinessUnitId { get; set; }
        public decimal ActivityAmount { get; set; }
        public decimal MaterialAmount { get; set; }
        public bool IsClosed { get; set; }
        public int BomLevel { get; set; }
        public long PeriodDataId { get; set; }
        public string CostType { get; set; }
        public bool IsRework { get; set; }
        public string Currency { get; set; }
        public decimal LotAmount { get; set; }
        public float? Ratio { get; set; }
        public string CostFrom { get; set; }
        public decimal ResourceAmount { get; set; }
        public decimal LossQty { get; set; }
        public string Label1 { get; set; }
        public string Label2 { get; set; }
        public string Label3 { get; set; }
        public string Label4 { get; set; }
        public string Label5 { get; set; }
        public string Label6 { get; set; }
        public string Label7 { get; set; }
        public string Label8 { get; set; }
        public string Label9 { get; set; }
        public string Label10 { get; set; }
        public string Label11 { get; set; }
        public string Label12 { get; set; }
        public string Label13 { get; set; }
        public string Label14 { get; set; }
        public string Label15 { get; set; }
        public decimal ProjectAmount { get; set; }
    }
}