// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ObjectClass
    {
        public ObjectClass()
        {
            EntityClassificationTree = new HashSet<EntityClassificationTree>();
            EntityParameter = new HashSet<EntityParameter>();
            EntityProperty = new HashSet<EntityProperty>();
            Resource = new HashSet<Resource>();
            ValueChain = new HashSet<ValueChain>();
            ValueObject = new HashSet<ValueObject>();
        }

        public long ObjectClassId { get; set; }
        public string ObjectClassNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public string Type { get; set; }
        public string EntityName { get; set; }
        public bool? AccumulateCost { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<EntityClassificationTree> EntityClassificationTree { get; set; }
        public virtual ICollection<EntityParameter> EntityParameter { get; set; }
        public virtual ICollection<EntityProperty> EntityProperty { get; set; }
        public virtual ICollection<Resource> Resource { get; set; }
        public virtual ICollection<ValueChain> ValueChain { get; set; }
        public virtual ICollection<ValueObject> ValueObject { get; set; }
    }
}