// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PartStockSum
    {
        public long PartStockId { get; set; }
        public decimal StockQtyForUnitCost0 { get; set; }
        public decimal StockQtyForUnitCost { get; set; }
        public decimal StockQtyEnd { get; set; }
        public decimal StockAmountInit { get; set; }
        public decimal StockAmountRtn { get; set; }
        public decimal StockAmountIn { get; set; }
        public decimal StockAmountOut { get; set; }
        public decimal StockAmountRwkIn { get; set; }
        public decimal StockAmountRwkOut { get; set; }
        public decimal StockAmountEnd { get; set; }
        public decimal UnitCostInit { get; set; }
        public decimal UnitCost0 { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitCostSupplier { get; set; }
        public decimal UnitCostActivity { get; set; }
        public decimal UnitCostResource { get; set; }
        public decimal UnitCostMoa { get; set; }
        public decimal UnitCostMom { get; set; }
        public decimal UnitCostPurchase { get; set; }
        public decimal UnitCostTransfer { get; set; }
        public decimal UnitCostSupplierInit { get; set; }
        public decimal UnitCostActivityInit { get; set; }
        public decimal UnitCostResourceInit { get; set; }
        public decimal UnitCostMoainit { get; set; }
        public decimal UnitCostMominit { get; set; }
        public decimal UnitCostPurchaseInit { get; set; }
        public decimal UnitCostTransferInit { get; set; }
        public decimal UnitCostSupplier0 { get; set; }
        public decimal UnitCostActivity0 { get; set; }
        public decimal UnitCostResource0 { get; set; }
        public decimal UnitCostMoa0 { get; set; }
        public decimal UnitCostMom0 { get; set; }
        public decimal UnitCostPurchase0 { get; set; }
        public decimal UnitCostTransfer0 { get; set; }
        public decimal SupplierAmountEnd { get; set; }
        public decimal ActivityAmountEnd { get; set; }
        public decimal ResourceAmountEnd { get; set; }
        public decimal PurchaseAmountEnd { get; set; }
        public decimal MoaamountEnd { get; set; }
        public decimal MomamountEnd { get; set; }
        public decimal TransferCostEnd { get; set; }
        public long? LastPeriodDataId { get; set; }
        public decimal UnitCostProjectInit { get; set; }
        public decimal UnitCostProject0 { get; set; }
        public decimal UnitCostProject { get; set; }
        public decimal ProjectAmountEnd { get; set; }
        public decimal UnitCostSo { get; set; }
        public decimal UnitCostActivitySo { get; set; }
        public decimal UnitCostResourceSo { get; set; }
        public decimal UnitCostSupplierSo { get; set; }
        public decimal UnitCostPurchaseSo { get; set; }
        public decimal UnitCostMoaso { get; set; }
        public decimal UnitCostMomso { get; set; }
        public decimal UnitCostTransferSo { get; set; }
        public decimal UnitCostProjectSo { get; set; }
        public decimal StockQtyForUnitCostSo { get; set; }
    }
}