// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PartStock
    {
        public PartStock()
        {
            InversePrePartStock = new HashSet<PartStock>();
        }

        public long PartStockId { get; set; }
        public string PartNo { get; set; }
        public long PeriodId { get; set; }
        public decimal StockQtyInit { get; set; }
        public decimal StockQtyRtn { get; set; }
        public decimal StockQtyIn { get; set; }
        public decimal PurchaseQtyIn { get; set; }
        public decimal TransferQtyIn { get; set; }
        public decimal StockQtyOut { get; set; }
        public decimal StockQtyRwkIn { get; set; }
        public decimal StockQtyRwkOut { get; set; }
        public decimal StockQtySoldOut { get; set; }
        public decimal TransferQtyOut { get; set; }
        public string Unit { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long BusinessUnitId { get; set; }
        public long? PrePartStockId { get; set; }
        public decimal SupplierAmountInit { get; set; }
        public decimal SupplierAmountRtn { get; set; }
        public decimal SupplierAmountIn { get; set; }
        public decimal SupplierAmountOut { get; set; }
        public decimal SupplierAmountRwkIn { get; set; }
        public decimal SupplierAmountRwkOut { get; set; }
        public decimal ActivityAmountInit { get; set; }
        public decimal ActivityAmountRtn { get; set; }
        public decimal ActivityAmountIn { get; set; }
        public decimal ActivityAmountOut { get; set; }
        public decimal ActivityAmountRwkIn { get; set; }
        public decimal ActivityAmountRwkOut { get; set; }
        public decimal ResourceAmountInit { get; set; }
        public decimal ResourceAmountRtn { get; set; }
        public decimal ResourceAmountIn { get; set; }
        public decimal ResourceAmountOut { get; set; }
        public decimal ResourceAmountRwkIn { get; set; }
        public decimal ResourceAmountRwkOut { get; set; }
        public decimal PurchaseAmountInit { get; set; }
        public decimal PurchaseAmountRtn { get; set; }
        public decimal PurchaseAmountIn { get; set; }
        public decimal PurchaseAmountOut { get; set; }
        public decimal PurchaseAmountRwkIn { get; set; }
        public decimal PurchaseAmountRwkOut { get; set; }
        public decimal MoaamountInit { get; set; }
        public decimal MoaamountRtn { get; set; }
        public decimal MoaamountIn { get; set; }
        public decimal MoaamountOut { get; set; }
        public decimal MoaamountRwkIn { get; set; }
        public decimal MoaamountRwkOut { get; set; }
        public decimal MomamountInit { get; set; }
        public decimal MomamountRtn { get; set; }
        public decimal MomamountIn { get; set; }
        public decimal MomamountOut { get; set; }
        public decimal MomamountRwkIn { get; set; }
        public decimal MomamountRwkOut { get; set; }
        public decimal TransferCostInit { get; set; }
        public decimal TransferCostRtn { get; set; }
        public decimal TransferCostIn { get; set; }
        public decimal TransferCostOut { get; set; }
        public decimal TransferCostRwkIn { get; set; }
        public decimal TransferCostRwkOut { get; set; }
        public decimal TransferPriceInit { get; set; }
        public decimal TransferPriceIn { get; set; }
        public decimal TransferPriceOut { get; set; }
        public long LastPeriodDataId { get; set; }
        public decimal? UnitCostStdActivity { get; set; }
        public decimal? UnitCostStdMaterial { get; set; }
        public string CostType { get; set; }
        public decimal PurchaseAmountEnd { get; set; }
        public decimal PurchaseQtyEnd { get; set; }
        public decimal LossQty { get; set; }
        public decimal LossAmount { get; set; }
        public decimal StockQtyDasmOut { get; set; }
        public decimal ProjectAmountInit { get; set; }
        public decimal ProjectAmountRtn { get; set; }
        public decimal ProjectAmountIn { get; set; }
        public decimal ProjectAmountOut { get; set; }
        public decimal ProjectAmountRwkIn { get; set; }
        public decimal ProjectAmountRwkOut { get; set; }
        public decimal StockQtyLastSoldRtn { get; set; }
        public decimal SoldAmountLastSoldRtn { get; set; }
        public decimal StockQtyThisSoldRtn { get; set; }
        public decimal BonousQty { get; set; }
        public int DataState { get; set; }
        public decimal MoramountIn { get; set; }
        public decimal MoramountRwkIn { get; set; }
        public decimal MopamountIn { get; set; }
        public decimal MopamountRwkIn { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Period Period { get; set; }
        public virtual PartStock PrePartStock { get; set; }
        public virtual ICollection<PartStock> InversePrePartStock { get; set; }
    }
}