// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PartStockMovementVer
    {
        public long PartStockMovementId { get; set; }
        public long PeriodId { get; set; }
        public long PeriodDataId { get; set; }
        public long BusinessUnitId { get; set; }
        public long? ActivityCenterId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public long MaterialId { get; set; }
        public long? ProjectId { get; set; }
        public long? ProductId { get; set; }
        public long? CustomerId { get; set; }
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public string Movement { get; set; }
        public string Reason1 { get; set; }
        public string Reason2 { get; set; }
        public string Reason3 { get; set; }
        public string Reason4 { get; set; }
        public string Reason5 { get; set; }
        public string Currency { get; set; }
    }
}