// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PeriodDataRunLog
    {
        public long PeriodDataRunLogId { get; set; }
        public string PeriodDataRunLogNo { get; set; }
        public long PeriodDataRunId { get; set; }
        public string LogType { get; set; }
        public string MessageNo { get; set; }
        public string MessageText { get; set; }
        public string MessageParam { get; set; }
        public string StackTrace { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }

        public virtual PeriodDataRun PeriodDataRun { get; set; }
    }
}