// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Period
    {
        public Period()
        {
            MoMaterialCost = new HashSet<MoMaterialCost>();
            MoProductCost = new HashSet<MoProductCost>();
            PartStock = new HashSet<PartStock>();
            PeriodData = new HashSet<PeriodData>();
        }

        public long PeriodId { get; set; }
        public string PeriodNo { get; set; }
        public long CompanyId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Quarter { get; set; }
        public int Yymm { get; set; }
        public long ActivePeriodDataId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public bool IsRuning { get; set; }
        public int Progress { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<MoMaterialCost> MoMaterialCost { get; set; }
        public virtual ICollection<MoProductCost> MoProductCost { get; set; }
        public virtual ICollection<PartStock> PartStock { get; set; }
        public virtual ICollection<PeriodData> PeriodData { get; set; }
    }
}