// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PeriodDataRun
    {
        public PeriodDataRun()
        {
            PeriodDataRunLog = new HashSet<PeriodDataRunLog>();
            PeriodDataRunPerf = new HashSet<PeriodDataRunPerf>();
        }

        public long PeriodDataRunId { get; set; }
        public string PeriodDataRunNo { get; set; }
        public long PeriodDataId { get; set; }
        public string Result { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? FinishTime { get; set; }
        public int? RunSecond { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? ExFileId { get; set; }

        public virtual PeriodData PeriodData { get; set; }
        public virtual ICollection<PeriodDataRunLog> PeriodDataRunLog { get; set; }
        public virtual ICollection<PeriodDataRunPerf> PeriodDataRunPerf { get; set; }
    }
}