// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PickListValue
    {
        public PickListValue()
        {
            InverseParentPickListValue = new HashSet<PickListValue>();
        }

        public long PickListValueId { get; set; }
        public string PickListValueNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public long PickListId { get; set; }
        public long? ParentPickListValueId { get; set; }

        public virtual PickListValue ParentPickListValue { get; set; }
        public virtual PickList PickList { get; set; }
        public virtual ICollection<PickListValue> InverseParentPickListValue { get; set; }
    }
}