// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PickList
    {
        public PickList()
        {
            EntityProperty = new HashSet<EntityProperty>();
            InverseParentPickList = new HashSet<PickList>();
            PickListValue = new HashSet<PickListValue>();
        }

        public long PickListId { get; set; }
        public string PickListNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public long? ParentPickListId { get; set; }
        public string DefaultValue { get; set; }

        public virtual Company Company { get; set; }
        public virtual PickList ParentPickList { get; set; }
        public virtual ICollection<EntityProperty> EntityProperty { get; set; }
        public virtual ICollection<PickList> InverseParentPickList { get; set; }
        public virtual ICollection<PickListValue> PickListValue { get; set; }
    }
}