// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ProductPeriodCost
    {
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long PeriodDataId { get; set; }
        public long ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal StdAmount { get; set; }
        public string Currency { get; set; }
        public string CostType { get; set; }
        public decimal UnitAmount { get; set; }
        public decimal StdUnitAmount { get; set; }
        public string ValueChain { get; set; }

        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Product { get; set; }
    }
}