// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ProjectCost
    {
        public ProjectCost()
        {
            ProjectCostAllocation = new HashSet<ProjectCostAllocation>();
        }

        public long ProjectCostId { get; set; }
        public long? LastProjectCostId { get; set; }
        public long? PrePeriodDataId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long ProjectId { get; set; }
        public long PeriodDataId { get; set; }
        public long BusinessUnitId { get; set; }
        public long? ResourceId { get; set; }
        public long? ActivityCenterId { get; set; }
        public long? MachineGroupId { get; set; }
        public long? ActivityId { get; set; }
        public string CostType { get; set; }
        public string Currency { get; set; }
        public decimal AmountEnd { get; set; }
        public decimal AmountIn { get; set; }
        public string ValueChain { get; set; }
        public decimal AllocatedAmountEnd { get; set; }
        public decimal AllocatedAmountIn { get; set; }
        public decimal AllocatedPointEnd { get; set; }
        public decimal AllocatedPointIn { get; set; }
        public decimal AllocatedQuantityEnd { get; set; }
        public decimal AllocatedQuantityIn { get; set; }
        public decimal AllocatedUnitAmount { get; set; }
        public decimal StdAmountEnd { get; set; }
        public decimal StdAmountIn { get; set; }
        public decimal AllocatedStdAmountEnd { get; set; }
        public decimal AllocatedStdAmountIn { get; set; }
        public decimal AllocatedStdUnitAmount { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual MachineGroup MachineGroup { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Project { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<ProjectCostAllocation> ProjectCostAllocation { get; set; }
    }
}