// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ProjectCostAllocation
    {
        public long ProjectCostAllocationId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long ProjectCostId { get; set; }
        public long? ProductId { get; set; }
        public long? CustomerId { get; set; }
        public decimal AllocationQuantity { get; set; }
        public decimal AllocationPoint { get; set; }
        public decimal AllocationAmount { get; set; }
        public decimal AllocationUnitAmount { get; set; }
        public decimal AllocationStdAmount { get; set; }
        public decimal AllocationStdUnitAmount { get; set; }
        public long? DriverId { get; set; }
        public float? Ratio { get; set; }
        public float? DriverValue { get; set; }
        public float? ComplexityValue { get; set; }
        public float? DriverValueInit { get; set; }
        public string Currency { get; set; }
        public bool AllocationToInv { get; set; }
        public long? BusinessUnitId { get; set; }
        public long? ManufactureOrderId { get; set; }

        public virtual ValueObject Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ValueObject ManufactureOrder { get; set; }
        public virtual ValueObject Product { get; set; }
        public virtual ProjectCost ProjectCost { get; set; }
    }
}