// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ProjectCostAllocationSum
    {
        public long PeriodDataId { get; set; }
        public long ProjectId { get; set; }
        public long? ProductId { get; set; }
        public long? CustomerId { get; set; }
        public long BusinessUnitId { get; set; }
        public decimal AllocationAmount { get; set; }
        public decimal AllocationUnitAmount { get; set; }
        public decimal AllocationStdAmount { get; set; }
        public decimal AllocationStdUnitAmount { get; set; }
        public string Currency { get; set; }
        public string ValueChain { get; set; }
        public long? ToBusinessUnitId { get; set; }
    }
}