// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ProjectCostAllocationToInvSum
    {
        public long PeriodDataId { get; set; }
        public long ProjectId { get; set; }
        public long ProductId { get; set; }
        public decimal AllocationAmount { get; set; }
        public decimal AllocationUnitAmount { get; set; }
        public decimal AllocationStdAmount { get; set; }
        public decimal AllocationStdUnitAmount { get; set; }
        public string Currency { get; set; }
        public long ToStockBusinessUnitId { get; set; }
    }
}