// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ProjectCostSum
    {
        public long ProjectCostSumId { get; set; }
        public long? LastProjectCostSumId { get; set; }
        public long PeriodDataId { get; set; }
        public long ProjectId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public decimal TotalProjectPoint { get; set; }
        public decimal ProjectAmountEnd { get; set; }
        public decimal ProjectAmountIn { get; set; }
        public decimal AllocationUnitAmount { get; set; }
        public decimal AllocationQuantityEnd { get; set; }
        public decimal AllocationAmountEnd { get; set; }
        public decimal AllocationPointEnd { get; set; }
        public decimal AllocationQuantityIn { get; set; }
        public decimal AllocationPointIn { get; set; }
        public decimal AllocationAmountIn { get; set; }
        public decimal ProjectStdAmountEnd { get; set; }
        public decimal ProjectStdAmountIn { get; set; }
        public decimal AllocationStdUnitAmount { get; set; }
        public decimal AllocationStdAmountEnd { get; set; }
        public decimal AllocationStdAmountIn { get; set; }
        public string Currency { get; set; }
        public bool? AutoAllocation { get; set; }

        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Project { get; set; }
    }
}