// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class PurchaseMaterial
    {
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long PeriodId { get; set; }
        public long BusinessUnitId { get; set; }
        public long MaterialId { get; set; }
        public long ProductId { get; set; }
        public string PartNo { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal RtnQuantity { get; set; }
        public decimal RtnAmount { get; set; }
        public bool IsUsed { get; set; }
    }
}