// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Reports
    {
        public long ReportsId { get; set; }
        public string ReportsNo { get; set; }
        public string Description { get; set; }
        public string ReportType { get; set; }
        public string ReportTitle { get; set; }
        public string ReportSubTitle { get; set; }
        public string ReportPath { get; set; }
        public string ActionLink { get; set; }
        public long AuthLevel { get; set; }
        public string Sqlfrom { get; set; }
        public string Sqlwhere { get; set; }
        public bool? OnDateRange { get; set; }
        public bool? IsPeriodNo { get; set; }
        public bool OnBussinessUnit { get; set; }
        public bool OnActitityCenter { get; set; }
        public bool OnActitity { get; set; }
    }
}