// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ResourceAdjustmentCost
    {
        public long ResourceAdjustmentCostId { get; set; }
        public long PeriodDataId { get; set; }
        public long ResourceId { get; set; }
        public long ActivityCenterId { get; set; }
        public string CostType { get; set; }
        public string Reason { get; set; }
        public decimal? Amount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? MachineGroupId { get; set; }
        public string SourceKey { get; set; }
        public long? ValueObjectId { get; set; }

        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual MachineGroup MachineGroup { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ValueObject ValueObject { get; set; }
    }
}