// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Resource
    {
        public Resource()
        {
            ActivityCenterCost = new HashSet<ActivityCenterCost>();
            BusinessUnitResource = new HashSet<BusinessUnitResource>();
            CustomerServiceCost = new HashSet<CustomerServiceCost>();
            ProjectCost = new HashSet<ProjectCost>();
            ResourceAdjustmentCost = new HashSet<ResourceAdjustmentCost>();
            ValueChain = new HashSet<ValueChain>();
            ValueObjectCost = new HashSet<ValueObjectCost>();
        }

        public long ResourceId { get; set; }
        public string ResourceNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public string ValueObjectType { get; set; }
        public long? ResourceDriverId { get; set; }
        public long? ServiceDriverId { get; set; }
        public long? ObjectClassId { get; set; }
        public string UserProperty1 { get; set; }
        public string UserProperty2 { get; set; }
        public string UserProperty3 { get; set; }
        public string UserProperty4 { get; set; }
        public string UserProperty5 { get; set; }
        public string UserProperty6 { get; set; }
        public string UserProperty7 { get; set; }
        public string UserProperty8 { get; set; }
        public string UserProperty9 { get; set; }
        public string UserProperty10 { get; set; }
        public string UserProperty11 { get; set; }
        public string UserProperty12 { get; set; }
        public string UserProperty13 { get; set; }
        public string UserProperty14 { get; set; }
        public string UserProperty15 { get; set; }
        public string UserProperty16 { get; set; }
        public string UserProperty17 { get; set; }
        public string UserProperty18 { get; set; }
        public string UserProperty19 { get; set; }
        public string UserProperty20 { get; set; }
        public string ResourceType1 { get; set; }
        public string ResourceType2 { get; set; }
        public string ResourceType3 { get; set; }
        public string ResourceType4 { get; set; }
        public string ResourceType5 { get; set; }
        public string ProductCostType { get; set; }

        public virtual Company Company { get; set; }
        public virtual ObjectClass ObjectClass { get; set; }
        public virtual Driver ResourceDriver { get; set; }
        public virtual Driver ServiceDriver { get; set; }
        public virtual ICollection<ActivityCenterCost> ActivityCenterCost { get; set; }
        public virtual ICollection<BusinessUnitResource> BusinessUnitResource { get; set; }
        public virtual ICollection<CustomerServiceCost> CustomerServiceCost { get; set; }
        public virtual ICollection<ProjectCost> ProjectCost { get; set; }
        public virtual ICollection<ResourceAdjustmentCost> ResourceAdjustmentCost { get; set; }
        public virtual ICollection<ValueChain> ValueChain { get; set; }
        public virtual ICollection<ValueObjectCost> ValueObjectCost { get; set; }
    }
}