// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class SalesOrderItem
    {
        public SalesOrderItem()
        {
            SalesOrderItemReturn = new HashSet<SalesOrderItemReturn>();
        }

        public long SalesOrderItemId { get; set; }
        public string SalesOrderNo { get; set; }
        public long PeriodDataId { get; set; }
        public long BusinessUnitId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CustomerId { get; set; }
        public long SalesActivityCenterId { get; set; }
        public string SoldBy { get; set; }
        public string Channel { get; set; }
        public string ItemNo { get; set; }
        public long ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public long ShippingBusinessUnitId { get; set; }
        public decimal ManufactureCost { get; set; }
        public decimal ProjectCost { get; set; }
        public decimal ServiceCost { get; set; }
        public string Label1 { get; set; }
        public string Label2 { get; set; }
        public string Label3 { get; set; }
        public string Label4 { get; set; }
        public string Label5 { get; set; }
        public decimal ResourcePeriodCost { get; set; }
        public decimal ActivityPeriodCost { get; set; }
        public decimal ProjectStdCost { get; set; }
        public decimal ServiceStdCost { get; set; }
        public decimal ActivityStdPeriodCost { get; set; }
        public decimal ResourceStdPeriodCost { get; set; }
        public string Currency { get; set; }
        public string Label6 { get; set; }
        public string Label7 { get; set; }
        public string Label8 { get; set; }
        public string Label9 { get; set; }
        public string Label10 { get; set; }
        public string Label11 { get; set; }
        public string Label12 { get; set; }
        public string Label13 { get; set; }
        public string Label14 { get; set; }
        public string Label15 { get; set; }
        public decimal ManufactureCostInit { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ValueObject Customer { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Product { get; set; }
        public virtual ActivityCenter SalesActivityCenter { get; set; }
        public virtual BusinessUnit ShippingBusinessUnit { get; set; }
        public virtual ICollection<SalesOrderItemReturn> SalesOrderItemReturn { get; set; }
    }
}