// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class SalesOrderSum
    {
        public long SalesOrderSumId { get; set; }
        public long PeriodDataId { get; set; }
        public long? BusinessUnitId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? CustomerId { get; set; }
        public long? ProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public long? ShippingBusinessUnitId { get; set; }
        public decimal ManufactureCost { get; set; }
        public decimal ProjectCost { get; set; }
        public decimal ServiceCost { get; set; }
        public decimal ResourcePeriodCost { get; set; }
        public decimal ActivityPeriodCost { get; set; }
        public decimal ProjectStdCost { get; set; }
        public decimal ServiceStdCost { get; set; }
        public decimal ActivityStdPeriodCost { get; set; }
        public decimal ResourceStdPeriodCost { get; set; }
        public string Currency { get; set; }
        public decimal ManufactureCostInit { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ValueObject Customer { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Product { get; set; }
    }
}