// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class SalesOrderItemReturn
    {
        public long SalesOrderItemReturnId { get; set; }
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long SalesOrderItemId { get; set; }
        public long OldSalesOrderItemId { get; set; }
        public decimal Quantity { get; set; }

        public virtual SalesOrderItem SalesOrderItem { get; set; }
    }
}