// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class Transaction
    {
        public long TransactionId { get; set; }
        public string TransactionNo { get; set; }
        public string Function { get; set; }
        public string Comment { get; set; }
        public string UserName { get; set; }
        public string FromNode { get; set; }
        public string ClientAppName { get; set; }
        public string ClientVersion { get; set; }
        public DateTime? ClientSendTime { get; set; }
        public DateTime? ActualActionTime { get; set; }
        public DateTime? SysStartTime { get; set; }
        public DateTime? SysEndTime { get; set; }
    }
}