// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorLogin.Data;
using BlazorLogin.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class User
    {
        public User()
        {
            Employee = new HashSet<Employee>();
            UserUserGroup = new HashSet<UserUserGroup>();
        }

        public long UserId { get; set; }
        public string UserNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string JobTitle { get; set; }
        public string Industry { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<UserUserGroup> UserUserGroup { get; set; }
    }
    public class UserDataSerive:IDataService<User>
    {
        private readonly TEMPLATE20Context context;

        public void Delete(User Entity)
        {
            throw new NotImplementedException();
        }

        public IQueryable<User> GetAll()
        {
            throw new NotImplementedException();
        }

        public void Insert(User Entity)
        {
            throw new NotImplementedException();
        }

        public User Read(Expression<Func<User, bool>> predicate)
        {
            throw new NotImplementedException();
        }

        public void SaveChanges()
        {
            throw new NotImplementedException();
        }

        public void Update(User Entity)
        {
            throw new NotImplementedException();
        }
    }
}