// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class User
    {
        public User()
        {
            Employee = new HashSet<Employee>();
            UserUserGroup = new HashSet<UserUserGroup>();
        }

        public long UserId { get; set; }
        public string UserNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string JobTitle { get; set; }
        public string Industry { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<UserUserGroup> UserUserGroup { get; set; }
    }
}