// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ValueObject
    {
        public ValueObject()
        {
            ActualWorkHourProduct = new HashSet<ActualWorkHour>();
            ActualWorkHourValueObject = new HashSet<ActualWorkHour>();
            CustomerServiceCostCustomer = new HashSet<CustomerServiceCost>();
            CustomerServiceCostProduct = new HashSet<CustomerServiceCost>();
            MoMaterialCostManufactureOrder = new HashSet<MoMaterialCost>();
            MoMaterialCostMaterial = new HashSet<MoMaterialCost>();
            MoProductCostManufactureOrder = new HashSet<MoProductCost>();
            MoProductCostProduct = new HashSet<MoProductCost>();
            ProductPeriodCost = new HashSet<ProductPeriodCost>();
            ProjectCost = new HashSet<ProjectCost>();
            ProjectCostAllocationCustomer = new HashSet<ProjectCostAllocation>();
            ProjectCostAllocationManufactureOrder = new HashSet<ProjectCostAllocation>();
            ProjectCostAllocationProduct = new HashSet<ProjectCostAllocation>();
            ProjectCostSum = new HashSet<ProjectCostSum>();
            ResourceAdjustmentCost = new HashSet<ResourceAdjustmentCost>();
            SalesOrderItemCustomer = new HashSet<SalesOrderItem>();
            SalesOrderItemProduct = new HashSet<SalesOrderItem>();
            SalesOrderSumCustomer = new HashSet<SalesOrderSum>();
            SalesOrderSumProduct = new HashSet<SalesOrderSum>();
            ValueObjectCostFromSupplier = new HashSet<ValueObjectCost>();
            ValueObjectCostProduct = new HashSet<ValueObjectCost>();
            ValueObjectCostScope = new HashSet<ValueObjectCostScope>();
            ValueObjectCostValueObject = new HashSet<ValueObjectCost>();
        }

        public long ValueObjectId { get; set; }
        public string ValueObjectNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long CompanyId { get; set; }
        public long? DriverId { get; set; }
        public long? AllocateToValueObjectId { get; set; }
        public long ObjectClassId { get; set; }
        public string UserProperty1 { get; set; }
        public string UserProperty2 { get; set; }
        public string UserProperty3 { get; set; }
        public string UserProperty4 { get; set; }
        public string UserProperty5 { get; set; }
        public string UserProperty6 { get; set; }
        public string UserProperty7 { get; set; }
        public string UserProperty8 { get; set; }
        public string UserProperty9 { get; set; }
        public string UserProperty10 { get; set; }
        public string UserProperty11 { get; set; }
        public string UserProperty12 { get; set; }
        public string UserProperty13 { get; set; }
        public string UserProperty14 { get; set; }
        public string UserProperty15 { get; set; }
        public string UserProperty16 { get; set; }
        public string UserProperty17 { get; set; }
        public string UserProperty18 { get; set; }
        public string UserProperty19 { get; set; }
        public string UserProperty20 { get; set; }
        public long? ClassificationId1 { get; set; }
        public long? ClassificationId2 { get; set; }
        public long? ClassificationId3 { get; set; }
        public long? ClassificationId4 { get; set; }
        public long? ClassificationId5 { get; set; }
        public long? ClassificationId6 { get; set; }
        public long? ClassificationId7 { get; set; }
        public long? ClassificationId8 { get; set; }
        public long? ClassificationId9 { get; set; }
        public long? ClassificationId10 { get; set; }
        public long? ActivityCenterId { get; set; }
        public bool? IsClosed { get; set; }
        public int? StartDate { get; set; }
        public decimal? PlanQty { get; set; }
        public long? ClosedPeriodId { get; set; }

        public virtual ActivityCenter ActivityCenter { get; set; }
        public virtual Company Company { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ObjectClass ObjectClass { get; set; }
        public virtual ICollection<ActualWorkHour> ActualWorkHourProduct { get; set; }
        public virtual ICollection<ActualWorkHour> ActualWorkHourValueObject { get; set; }
        public virtual ICollection<CustomerServiceCost> CustomerServiceCostCustomer { get; set; }
        public virtual ICollection<CustomerServiceCost> CustomerServiceCostProduct { get; set; }
        public virtual ICollection<MoMaterialCost> MoMaterialCostManufactureOrder { get; set; }
        public virtual ICollection<MoMaterialCost> MoMaterialCostMaterial { get; set; }
        public virtual ICollection<MoProductCost> MoProductCostManufactureOrder { get; set; }
        public virtual ICollection<MoProductCost> MoProductCostProduct { get; set; }
        public virtual ICollection<ProductPeriodCost> ProductPeriodCost { get; set; }
        public virtual ICollection<ProjectCost> ProjectCost { get; set; }
        public virtual ICollection<ProjectCostAllocation> ProjectCostAllocationCustomer { get; set; }
        public virtual ICollection<ProjectCostAllocation> ProjectCostAllocationManufactureOrder { get; set; }
        public virtual ICollection<ProjectCostAllocation> ProjectCostAllocationProduct { get; set; }
        public virtual ICollection<ProjectCostSum> ProjectCostSum { get; set; }
        public virtual ICollection<ResourceAdjustmentCost> ResourceAdjustmentCost { get; set; }
        public virtual ICollection<SalesOrderItem> SalesOrderItemCustomer { get; set; }
        public virtual ICollection<SalesOrderItem> SalesOrderItemProduct { get; set; }
        public virtual ICollection<SalesOrderSum> SalesOrderSumCustomer { get; set; }
        public virtual ICollection<SalesOrderSum> SalesOrderSumProduct { get; set; }
        public virtual ICollection<ValueObjectCost> ValueObjectCostFromSupplier { get; set; }
        public virtual ICollection<ValueObjectCost> ValueObjectCostProduct { get; set; }
        public virtual ICollection<ValueObjectCostScope> ValueObjectCostScope { get; set; }
        public virtual ICollection<ValueObjectCost> ValueObjectCostValueObject { get; set; }
    }
}