// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ValueObjectCostScope
    {
        public long ValueObjectCostId { get; set; }
        public long ToValueObjectId { get; set; }
        public float? DriverValue { get; set; }

        public virtual ValueObject ToValueObject { get; set; }
        public virtual ValueObjectCost ValueObjectCost { get; set; }
    }
}