// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ValueChain
    {
        public long ValueChainId { get; set; }
        public string ValueChainNo { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long ObjectClassId { get; set; }
        public long? ResourceId { get; set; }
        public long? ActivityId { get; set; }
        public long CompanyId { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Company Company { get; set; }
        public virtual ObjectClass ObjectClass { get; set; }
        public virtual Resource Resource { get; set; }
    }
}