// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorLogin.Models
{
    public partial class ValueObjectCost
    {
        public ValueObjectCost()
        {
            ValueObjectCostScope = new HashSet<ValueObjectCostScope>();
        }

        public long ValueObjectCostId { get; set; }
        public long PeriodDataId { get; set; }
        public long? ResourceId { get; set; }
        public long ValueObjectId { get; set; }
        public long ObjectClassId { get; set; }
        public string ValueChain { get; set; }
        public long? DriverId { get; set; }
        public string CostType { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public decimal StdAmount { get; set; }
        public float? Ratio { get; set; }
        public float? DriverValue { get; set; }
        public long? OwnerActivityCenterId { get; set; }
        public long? ActivityCostId { get; set; }
        public string Description { get; set; }
        public long? SecurityGroupId { get; set; }
        public string SysState { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public long? TransactionId { get; set; }
        public long? ProductId { get; set; }
        public string SourceKey { get; set; }
        public float? ComplexityValue { get; set; }
        public long BusinessUnitId { get; set; }
        public long? FromSupplierId { get; set; }
        public float? DriverValueInit { get; set; }
        public string Label1 { get; set; }
        public string Label2 { get; set; }
        public string Label3 { get; set; }
        public string Label4 { get; set; }
        public string Label5 { get; set; }
        public long? ActivityId { get; set; }
        public long? MachineGroupId { get; set; }
        public string Label6 { get; set; }
        public string Label7 { get; set; }
        public string Label8 { get; set; }
        public string Label9 { get; set; }
        public string Label10 { get; set; }
        public string Label11 { get; set; }
        public string Label12 { get; set; }
        public string Label13 { get; set; }
        public string Label14 { get; set; }
        public string Label15 { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual ValueObject FromSupplier { get; set; }
        public virtual ActivityCenter OwnerActivityCenter { get; set; }
        public virtual PeriodData PeriodData { get; set; }
        public virtual ValueObject Product { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ValueObject ValueObject { get; set; }
        public virtual ICollection<ValueObjectCostScope> ValueObjectCostScope { get; set; }
    }
}